name: datalocal_for_firestore
description: "Flutter local data with integration with firestore saved with state."
repository: "https://github.com/lamun-my-id/datalocal_for_firestore.git"
version: 1.0.31
# test    : dart pub publish --dry-run
# deploy  : dart pub publish 
# flutter pub upgrade --major-versions

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.4.4
  datalocal: ^1.0.31
  # datalocal:
    # path: ../data-state
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/lib/firebase_options.dart
  - /example/macos/Runner/GoogleService-Info.plist